
default: &default
  adapter: yugabytedb
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ysql_active_record
  username: yugabyte
  password:
  host: 127.0.0.1
  port: 5433
  load_balance: true

production:
  <<: *default
  database: ysql_active_record
  username: ror
  password: <%= ENV['ROR_DATABASE_PASSWORD'] %>
