/*
 * This file is generated by jOOQ.
 */
package com.yugabyte.jooqdemo.db;


import com.yugabyte.jooqdemo.db.tables.OrderLines;
import com.yugabyte.jooqdemo.db.tables.Orders;
import com.yugabyte.jooqdemo.db.tables.Products;
import com.yugabyte.jooqdemo.db.tables.Users;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in jooq.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.2",
        "schema version:jooq_1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.order_lines</code>.
     */
    public static final OrderLines ORDER_LINES = OrderLines.ORDER_LINES;

    /**
     * The table <code>jooq.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>jooq.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>jooq.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
