source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'rails', '7.1.3.4'
gem 'activerecord-yugabytedb-adapter', '~> 7.1.3.4'
gem 'sprockets-rails', '~> 3.0.0'
gem 'pg', '~> 1.4.4'
gem 'yugabytedb-ysql', '~> 0.4'
gem 'puma', '~> 5.6.5'
gem 'bootsnap', '>= 1.1.0', require: false
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.7.1'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.1.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
