alter table employee_territories drop constraint FK8wpb46fi1pg88rdc347so4pdp;
alter table employee_territories drop constraint FKdwg0nlt5cm59rapb2ve98hnk8;
alter table order_details drop constraint FKjyu2qbqt8gnvno9oe9j2s2ldk;
alter table order_details drop constraint FK4q98utpd73imf4yhttm3w0eax;
alter table orders drop constraint FKpxtb8awmi0dk6smoh2vp1litg;
alter table orders drop constraint FKfhl8bv0xn3sj33q2f3scf1bq6;
alter table orders drop constraint FK78rwh0ph68ixeoiwax3v77vqt;
alter table products drop constraint FKog2rp4qthbtt2lfyhfo32lsw9;
alter table products drop constraint FK6i174ixi9087gcvvut45em7fd;
alter table territories drop constraint FKbhyhwf2ccxh7ejt0696epikdq;
drop table if exists categories cascade;
drop table if exists customers cascade;
drop table if exists employee_territories cascade;
drop table if exists employees cascade;
drop table if exists order_details cascade;
drop table if exists orders cascade;
drop table if exists products cascade;
drop table if exists region cascade;
drop table if exists shippers cascade;
drop table if exists suppliers cascade;
drop table if exists territories cascade;
drop table if exists us_states cascade;
drop table if exists users cascade;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start 1 increment 1;
create table categories (category_id int4 not null, category_name varchar(15) not null, description varchar(100) not null, primary key (category_id));
create table customers (customer_id int4 not null, address varchar(60), city varchar(15), company_name varchar(40) not null, contact_name varchar(30), country varchar(15), fax varchar(24), phone varchar(24), postal_code varchar(10), region varchar(15), primary key (customer_id));
create table employee_territories (employeeId int4 not null, territoryId varchar(255) not null, employee_id int4, territory_id varchar(255), primary key (employeeId, territoryId));
create table employees (employee_id int4 not null, address varchar(60), birth_date varchar(255), city varchar(15), country varchar(15), extension varchar(4), first_name varchar(10) not null, hire_date varchar(255), home_phone varchar(24), last_name varchar(20) not null, notes TEXT, photo_path varchar(255), postal_code varchar(10), region varchar(15), reports_to int4, title varchar(30), title_of_courtesy varchar(25), primary key (employee_id));
create table order_details (order_id int4 not null, product_id int4 not null, Discount float8 not null, Quantity int4 not null, UnitPrice float8 not null, primary key (order_id, product_id));
create table orders (order_id int4 not null, freight float4, order_date date, required_date date, ship_address varchar(60), ship_city varchar(15), ship_country varchar(15), ship_name varchar(40), ship_postal_code varchar(10), ship_region varchar(15), shipped_date date, customer_id int4, employee_id int4, shipVia int4, primary key (order_id));
create table products (product_id int4 not null, discontinued int4 not null, product_name varchar(40) not null, quantity_per_unit varchar(20) not null, unit_price float8 not null, units_in_stock int4 not null, units_on_order int4, category_id int4, supplier_id int4, primary key (product_id));
create table region (region_id int4 not null, region_description varchar(255), primary key (region_id));
create table shippers (shipper_id int4 not null, company_name varchar(40), phone varchar(24), primary key (shipper_id));
create table suppliers (supplierID int4 not null, City varchar(15), CompanyName varchar(40) not null, ContactName varchar(30), Country varchar(15), primary key (supplierID));
create table territories (territory_id varchar(255) not null, territory_description varchar(255), region_id int4, primary key (territory_id));
create table us_states (state_id int4 not null, state_abbr varchar(2), state_name varchar(100), state_region varchar(50), primary key (state_id));
create table users (userId  bigserial not null, firstName varchar(255), lastName varchar(255), userEmail varchar(255), primary key (userId));
alter table employee_territories add constraint FK8wpb46fi1pg88rdc347so4pdp foreign key (employee_id) references employees;
alter table employee_territories add constraint FKdwg0nlt5cm59rapb2ve98hnk8 foreign key (territory_id) references territories;
alter table order_details add constraint FKjyu2qbqt8gnvno9oe9j2s2ldk foreign key (order_id) references orders;
alter table order_details add constraint FK4q98utpd73imf4yhttm3w0eax foreign key (product_id) references products;
alter table orders add constraint FKpxtb8awmi0dk6smoh2vp1litg foreign key (customer_id) references customers;
alter table orders add constraint FKfhl8bv0xn3sj33q2f3scf1bq6 foreign key (employee_id) references employees;
alter table orders add constraint FK78rwh0ph68ixeoiwax3v77vqt foreign key (shipVia) references shippers;
alter table products add constraint FKog2rp4qthbtt2lfyhfo32lsw9 foreign key (category_id) references categories;
alter table products add constraint FK6i174ixi9087gcvvut45em7fd foreign key (supplier_id) references suppliers;
alter table territories add constraint FKbhyhwf2ccxh7ejt0696epikdq foreign key (region_id) references region;
