package model

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type OrderLine struct {
	Order     Order     `gorm:"association_foreignkey:OrderId;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
	OrderId   uuid.UUID `gorm:"primary_key"`
	Product   Product   `gorm:"association_foreignkey:ProductId;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
	ProductId int64     `gorm:"primary_key" json:"productId"`
	Units     int       `json:"units"`
}

func (OrderLine) TableName() string {
	return "orderline"
}

type Order struct {
	OrderId    uuid.UUID   `gorm:"primary_key;AUTO_INCREMENT"`
	OrderTime  time.Time   `gorm:"default:CURRENT_TIMESTAMP"`
	OrderTotal float64     `gorm:"type:numeric(10,2)"`
	User       User        `gorm:"association_foreignkey:UserId;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`
	UserId     int64       `json:"userId"`
	Products   []OrderLine `json:"products"`
}

/* BeforeCreate will set an autogenerated UUID. */
func (order *Order) BeforeCreate(db *gorm.DB) error {
	uuid, err := uuid.NewRandom()
	if err != nil {
		return err
	}
	db.Statement.SetColumn("OrderId", uuid)
	return nil
}
